### PR TITLE
fix: error if characters outside of the Latin1 range.

### PR DESCRIPTION
**Pull request by richex-cn**
It doesn't work when the user name in my entry contains characters other than Latin1. So I fixed this problem in a simple way.

image

### CODE REVIEW

**Comment by belaviyo** [comment]
Can you confirm `atob(encodeURIComponent())` works? If so please update to it.

**Comment by richex-cn** [comment]
> Can you confirm `atob(encodeURIComponent())` works? If so please update to it.

I updated the code, The test on my equipment is normal.

I wonder why atob is necessary?

**Comment by belaviyo** [comment]
> I wonder why the Base64 encoding is necessary?

Maybe redundant. Since the entire `v2.js` will be deprecated soon, I don't mind having it for now.

**Comment by richex-cn** [comment]
Great, Look forward to the next new version~

**Pull request merged**
