### PR TITLE
Improve URL search in local KeePass file

### PR DESCRIPTION
**Pull request by HS24**
This change improves searching for sub domains.

For example if the KeePass file contains an entry for `example.com`, but you visit `www.example.com`, then the entry would match and the entry would be suggested.

### CODE REVIEW

**Comment by belaviyo** [comment]
Nice, I would say rewrite the code using the [tld.js](https://github.com/thom4parisot/tld.js) library. The task of accurately determining the domain from a given hostname in code is extremely challenging.

**Comment by belaviyo** [comment]
https://cdnjs.cloudflare.com/ajax/libs/tldjs/2.3.1/tld.js

**Comment by HS24** [comment]
Good idea, thank you! This improves especially complex domains like `s3.amazonaws.com`.
I added the tld.js library and specified the domain check. 
Now you can specify in KeePass either the exact subdomain (e.g. `www.example.com`) or the root domain (`example.com`). The protocol is optional now.

If you now specify an exact subdomain in KeePass like `other.example.com`, this would not be suggested for the site `www.example.com`.
If you specify only the domain `example.com`, then this entry would be suggested for both `www.example.com` and `other.example.com`.

**Comment by belaviyo** [comment]
Looks good to me. Thanks!

**Pull request merged**
